language: go
go:
    - 1.13.4
    - tip
matrix:
  allow_failures:
    - go: tip

notifications:
    email:
        recipients: dean.karn@gmail.com
        on_success: change
        on_failure: always

before_install:
  - go get -u github.com/go-playground/overalls
  - go get -u github.com/mattn/goveralls
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/gordonklaus/ineffassign
  - go get -u github.com/client9/misspell/cmd/misspell

before_script:
  - go vet ./...

script:
 - gofmt -d -s .
 - ineffassign ./
 - find . -type f | xargs misspell -source=text
 - go test -race ./...

after_success: |
  [ $TRAVIS_GO_VERSION = 1.13.4 ] &&
  overalls -project="github.com/go-playground/mold" -covermode=count -ignore=.git,_examples -debug &&
  goveralls -coverprofile=overalls.coverprofile -service travis-ci -repotoken $COVERALLS_TOKEN